syntax = "proto3";

package trading;

option go_package = "github.com/jst-Frenzy/iot/backend/dataController/api/grpc/gen;dataController";

service DeviceService {
  rpc OnPump(OnPumpRequest) returns (OnPumpResponse);
  rpc OffPump(OffPumpRequest) returns (OffPumpResponse);
  rpc OnFan(OnFanRequest) returns (OnFanResponse);
  rpc OffFan(OffFanRequest) returns (OffFanResponse);
}

message OnPumpRequest{}
message OnPumpResponse{}

message OffPumpRequest{}
message OffPumpResponse{}

message OnFanRequest{}
message OnFanResponse{}

message OffFanRequest{}
message OffFanResponse{}
